version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/club-0.0.1-SNAPSHOT.jar #인스턴스에서 파일이 저장될 위치
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: start.sh
      timeout: 60
      runas: root