spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: myadmin
    password: jyp1399@

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
    ddl-auto: update
